# Generated by Django 4.1.7 on 2023-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_table',
            name='deptno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp_table',
            name='empno',
            field=models.IntegerField(unique=True),
        ),
    ]
